#!/bin/bash

build() {
    add_module uinput
    add_binary deckrypt_input
    add_runscript
}

help() {
    cat <<HELPEOF
Provide game controller combinations as a password for LUKS decryption.
HELPEOF
}
